{{config (materialized = 'ephemeral')}}

WITH date_limits AS (
	SELECT MIN(CREATED_AT::DATE) AS MIN_DT, MAX(CREATED_AT::DATE) AS MAX_DT FROM {{ ref('stg_raw__candidates') }}
	UNION ALL
	SELECT MIN(UPDATED_AT::DATE) AS MIN_DT, MAX(UPDATED_AT::DATE) AS MAX_DT FROM {{ ref('stg_raw__candidates') }}
	UNION ALL
	SELECT MIN(CREATED_AT::DATE) AS MIN_DT, MAX(CREATED_AT::DATE) AS MAX_DT FROM {{ ref('stg_raw__employees') }}
	UNION ALL
	SELECT MIN(UPDATED_AT::DATE) AS MIN_DT, MAX(UPDATED_AT::DATE) AS MAX_DT FROM {{ ref('stg_raw__employees') }}
	UNION ALL
	SELECT MIN(WORK_START_AT::DATE) AS MIN_DT, MAX(WORK_START_AT::DATE) AS MAX_DT FROM {{ ref('stg_raw__employees') }}
	UNION ALL
	SELECT MIN(WORK_END_AT::DATE) AS MIN_DT, MAX(WORK_END_AT::DATE) AS MAX_DT FROM {{ ref('stg_raw__employees') }}
	UNION ALL
	SELECT MIN(CREATED_AT::DATE) AS MIN_DT, MAX(CREATED_AT::DATE) AS MAX_DT FROM {{ ref('stg_raw__interviews') }}
	UNION ALL
	SELECT MIN(UPDATED_AT::DATE) AS MIN_DT, MAX(UPDATED_AT::DATE) AS MAX_DT FROM {{ ref('stg_raw__interviews') }}
	UNION ALL
	SELECT MIN(CREATED_AT::DATE) AS MIN_DT, MAX(CREATED_AT::DATE) AS MAX_DT FROM {{ ref('stg_raw__job_functions') }}
	UNION ALL
	SELECT MIN(UPDATED_AT::DATE) AS MIN_DT, MAX(UPDATED_AT::DATE) AS MAX_DT FROM {{ ref('stg_raw__job_functions') }}
	UNION ALL
	SELECT MIN(CREATED_AT::DATE) AS MIN_DT, MAX(CREATED_AT::DATE) AS MAX_DT FROM {{ ref('stg_raw__skills') }}
	UNION ALL
	SELECT MIN(UPDATED_AT::DATE) AS MIN_DT, MAX(UPDATED_AT::DATE) AS MAX_DT FROM {{ ref('stg_raw__skills') }}
	UNION ALL
	SELECT CURRENT_DATE()::DATE AS MIN_DT, CURRENT_DATE()::DATE AS MAX_DT
),
final AS (
	SELECT
		MIN(MIN_DT) AS MIN_DATE,
		MAX(MAX_DT) AS MAX_DATE
	FROM date_limits
	WHERE MIN_DT IS NOT NULL
)
SELECT *
FROM final
